### ISSUE TITLE
Why the training effect of using your own data set is very poor

### ISSUE THREAD

**Issue by Haveoneriver** [peteryuX/esrgan-tf2#1]

**Comment by peteryuX** [comment]
Hi @Haveoneriver~ May you please explain the issue more clearly?

**Comment by Haveoneriver** [comment]
Hello, it's like this. I use my own data for training. The training effect is very poor, but it's good to use div2k data for training. I see the code and there's nothing to change, right?

**Comment by peteryuX** [comment]
Okay, thanks for explaining. Did the poor training effect mean the training error cannot be convergence? It appeared in both the PSNR-pretrain and ESGAN fintuning? Generally, the code don't need to modified... but I think if the dataset size is not similar to DIV2K, the hyper parameters should be take care.

**Comment by Haveoneriver** [comment]
Thank you for your answer. The poor effect I mentioned is that the image generated by SR after the same number of iterations is different from the image that can Sr on div2k. It's very strange in my own data, and relatively normal in div2k. I try to override the parameters
